name: Publicar App Bolões Loterias no GitHub Pages
on:
  push:
    branches: [ master, main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Compilar o Projeto
        run: dotnet publish -c Release -o release

      - name: Ajustar Base Href para GitHub Pages
        # Troque para letras minúsculas aqui se o link do seu repositório for minúsculo
        run: sed -i 's|<base href="/" />|<base href="/AppBoloesLoterias/" />|g' release/wwwroot/index.html

      - name: Criar página 404 para roteamento SPA do Blazor
        # Esta é a linha mágica que resolve os problemas de navegação no GitHub Pages
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Evitar bloqueio do GitHub (Jekyll)
        run: touch release/wwwroot/.nojekyll

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
